<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PHX-ISHARAF" ignored="10" name="Free CRM App Test Cases" tests="12" failures="2" timestamp="22 Mar 2020 18:38:29 GMT" time="1768.162" errors="0">
  <testcase name="scheduleMeetingviaNextAction" time="137.111" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="scheduleMeetingviaNextAction" time="143.787" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="scheduleMeetingviaNextAction" time="135.245" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="scheduleMeetingviaNextAction" time="125.137" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="scheduleMeetingviaNextAction" time="181.92" classname="com.crm.qa.testcases.BranchOpportunityTest">
    <skipped/>
  </testcase> <!-- scheduleMeetingviaNextAction -->
  <testcase name="scheduleMeetingviaNextAction" time="137.076" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="scheduleMeetingviaNextAction" time="133.866" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="scheduleMeetingviaNextAction" time="132.556" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="scheduleMeetingviaNextAction" time="139.128" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="scheduleMeetingviaNextAction" time="138.432" classname="com.crm.qa.testcases.BranchOpportunityTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Stage Status Value is not correct expected [Initial Appointment] but found [Attempting]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Stage Status Value is not correct expected [Initial Appointment] but found [Attempting]
	at com.crm.qa.pages.Opportunities.validateOpttyforStageStatus(Opportunities.java:731)
	at com.crm.qa.testcases.BranchOpportunityTest.scheduleMeetingviaNextAction(BranchOpportunityTest.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- scheduleMeetingviaNextAction -->
  <testcase name="scheduleMeetingviaNextAction" time="136.575" classname="com.crm.qa.testcases.BranchOpportunityTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Stage Status Value is not correct expected [Initial Appointment] but found [Attempting]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Stage Status Value is not correct expected [Initial Appointment] but found [Attempting]
	at com.crm.qa.pages.Opportunities.validateOpttyforStageStatus(Opportunities.java:731)
	at com.crm.qa.testcases.BranchOpportunityTest.scheduleMeetingviaNextAction(BranchOpportunityTest.java:176)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- scheduleMeetingviaNextAction -->
  <testcase name="scheduleMeetingviaNextAction" time="139.092" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="moveStageStatusManually" time="0.0" classname="com.crm.qa.testcases.BranchOpportunityTest">
    <ignored/>
  </testcase> <!-- moveStageStatusManually -->
  <testcase name="logacall_Reached_StageClosedLost" time="0.0" classname="com.crm.qa.testcases.BranchOpportunityTest">
    <ignored/>
  </testcase> <!-- logacall_Reached_StageClosedLost -->
  <testcase name="opttyClosedLost_viaAPI" time="0.0" classname="com.crm.qa.testcases.BranchOpportunityTest">
    <ignored/>
  </testcase> <!-- opttyClosedLost_viaAPI -->
  <testcase name="logacall_Reached_Optty" time="0.0" classname="com.crm.qa.testcases.BranchOpportunityTest">
    <ignored/>
  </testcase> <!-- logacall_Reached_Optty -->
  <testcase name="createBranchOptty_viaAPI" time="0.0" classname="com.crm.qa.testcases.BranchOpportunityTest">
    <ignored/>
  </testcase> <!-- createBranchOptty_viaAPI -->
  <testcase name="createNewFinancialAccount_BMOptty" time="0.0" classname="com.crm.qa.testcases.BranchOpportunityTest">
    <ignored/>
  </testcase> <!-- createNewFinancialAccount_BMOptty -->
  <testcase name="enrollment_BM" time="0.0" classname="com.crm.qa.testcases.BranchOpportunityTest">
    <ignored/>
  </testcase> <!-- enrollment_BM -->
  <testcase name="logacall_notReached_Optty" time="0.0" classname="com.crm.qa.testcases.BranchOpportunityTest">
    <ignored/>
  </testcase> <!-- logacall_notReached_Optty -->
  <testcase name="scheduleMeetingandthenCloseMeeting" time="0.0" classname="com.crm.qa.testcases.BranchOpportunityTest">
    <ignored/>
  </testcase> <!-- scheduleMeetingandthenCloseMeeting -->
  <testcase name="exp" time="0.0" classname="com.crm.qa.testcases.BranchOpportunityTest">
    <ignored/>
  </testcase> <!-- exp -->
</testsuite> <!-- Free CRM App Test Cases -->
