<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite guice-stage="DEVELOPMENT" name="Failed suite [FREE CRM Application Test Automation Test Suite]">
  <listeners>
    <listener class-name="com.qa.EventListener.TestListener"/>
    <listener class-name="com.qa.EventListener.FailureRetryListener"/>
  </listeners>
  <test name="Free CRM App Test Cases(failed)">
    <classes>
      <class name="com.crm.qa.testcases.LogActivityTest">
        <methods>
          <include name="tearDown"/>
          <include name="UpdatePrimaryAccountdetails" invocation-numbers="0"/>
          <include name="reachedwithBusinessLead_ScheduleTodo" invocation-numbers="1"/>
          <include name="validateEmail" invocation-numbers="0 0 1 1"/>
          <include name="setUp"/>
          <include name="UpdateSpouseAccountdetails" invocation-numbers="1"/>
          <include name="UnplannedMeeting_withOutcome_Cancelled_multipleUsers" invocation-numbers="0"/>
        </methods>
      </class> <!-- com.crm.qa.testcases.LogActivityTest -->
    </classes>
  </test> <!-- Free CRM App Test Cases(failed) -->
</suite> <!-- Failed suite [FREE CRM Application Test Automation Test Suite] -->
