<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="PHX-ISHARAF" name="com.crm.qa.testcases.BranchOpportunityTest" tests="15" failures="0" timestamp="11 Mar 2020 20:46:31 GMT" time="1650.337" errors="1">
  <testcase name="logacall_notReached_Optty" time="105.909" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="moveStageStatusManually" time="90.032" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="logacall_notReached_Optty" time="97.457" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="opttyClosedLost_viaAPI" time="95.092" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="scheduleMeetingandthenCloseMeeting" time="115.487" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="logacall_Reached_StageClosedLost" time="100.883" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="scheduleMeetingviaNextAction" time="145.629" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="scheduleMeetingviaNextAction" time="107.890" classname="com.crm.qa.testcases.BranchOpportunityTest">
    <skipped/>
  </testcase> <!-- scheduleMeetingviaNextAction -->
  <testcase name="opttyClosedLost_viaAPI" time="95.226" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="enrollment_BM" time="136.626" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="scheduleMeetingviaNextAction" time="113.805" classname="com.crm.qa.testcases.BranchOpportunityTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.support.events.EventFiringWebDriver.extractInterfaces(EventFiringWebDriver.java:121)
	at org.openqa.selenium.support.events.EventFiringWebDriver.access$500(EventFiringWebDriver.java:67)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.<init>(EventFiringWebDriver.java:343)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.<init>(EventFiringWebDriver.java:335)
	at org.openqa.selenium.support.events.EventFiringWebDriver.createWebElement(EventFiringWebDriver.java:308)
	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:191)
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy12.isDisplayed(Unknown Source)
	at org.openqa.selenium.support.ui.ExpectedConditions.elementIfVisible(ExpectedConditions.java:302)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$100(ExpectedConditions.java:44)
	at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:288)
	at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:285)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:209)
	at com.crm.qa.util.TestUtil.waitUntilElementVisible(TestUtil.java:141)
	at com.crm.qa.pages.Opportunities.scheduleMeetingusingNextAction(Opportunities.java:534)
	at com.crm.qa.testcases.BranchOpportunityTest.scheduleMeetingviaNextAction(BranchOpportunityTest.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- scheduleMeetingviaNextAction -->
  <testcase name="moveStageStatusManually" time="96.181" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="scheduleMeetingandthenCloseMeeting" time="103.979" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="logacall_Reached_StageClosedLost" time="119.275" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
  <testcase name="enrollment_BM" time="126.866" classname="com.crm.qa.testcases.BranchOpportunityTest"/>
</testsuite> <!-- com.crm.qa.testcases.BranchOpportunityTest -->
